---
title: "McCarthy Scores by SNP"
author: "Melissa Chapnick"
date: "2022-10-26"
output: html_document
---
```{r}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, include=TRUE)
```

```{r}
#Set filepaths
POSGRADanalyticlocation<-here::here("derived_data/POSGRADdata_merge_analytic.csv")

#Read in data
POSGRADanalytic<-read.csv(POSGRADanalyticlocation,header = TRUE)
```

The following graphs examine the distributions of cognitive outcome scores for children in the POSGRAD trial.

```{r}
library(ggplot2)
library(dplyr)
library(knitr)

#Examine distributions of McCarthy Scores

#Verbal
ggplot(POSGRADanalytic,aes(x=V))+
  geom_histogram(bins=50, fill="#69b3a2", color="#69b3a2")+
  ggtitle("Distribution of McCarthy Verbal Scores")+
  xlab("McCarthy Raw Verbal Score")

summary(POSGRADanalytic$V)

#Perceptual
ggplot(POSGRADanalytic,aes(x=P))+
  geom_histogram(bins=50, fill="#69b3a2", color="#69b3a2")+
  ggtitle("Distribution of McCarthy Perceptual Scores")+
  xlab("McCarthy Raw Perceptual Score")

summary(POSGRADanalytic$P)

#Quantitative
ggplot(POSGRADanalytic,aes(x=C))+
  geom_histogram(bins=50, fill="#69b3a2", color="#69b3a2")+
  ggtitle("Distribution of McCarthy Quantitative Scores")+
  xlab("McCarthy Raw Quantitative Score")

summary(POSGRADanalytic$C)

#Composite (Verbal, Perceptive, Quantitative)
ggplot(POSGRADanalytic,aes(x=VPC))+
  geom_histogram(bins=50, fill="#69b3a2", color="#69b3a2")+
  ggtitle("Distribution of McCarthy Composite Scores")+
  xlab("McCarthy Composite Score")

summary(POSGRADanalytic$VPC)

#Memory
ggplot(POSGRADanalytic,aes(x=Mem))+
  geom_histogram(bins=50, fill="#69b3a2", color="#69b3a2")+
  ggtitle("Distribution of McCarthy Memory Scores")+
  xlab("McCarthy Raw Memory Score")

summary(POSGRADanalytic$Mem)

#Motor
ggplot(POSGRADanalytic,aes(x=Mot))+
  geom_histogram(bins=50, fill="#69b3a2", color="#69b3a2")+
  ggtitle("Distribution of McCarthy Memory Scores")+
  xlab("McCarthy Raw Memory Score")

summary(POSGRADanalytic$Mot)

```

```{r}
#McCarthy Scores by SNP, check for differences with ANOVA

```

